<?php

/**
 * @file
 *   Installation file
 *
 * @version: $Id: account_profile.install,v 1.1.2.1 2010/08/18 15:15:57 kenorb Exp $
 *
 * @developers:
 *    Rafal Wieczorek <kenorb@gmail.com>
 */
/**
 * Implementation of hook_uninstall().
 */
function account_profile_uninstall() {
  variable_del('account_profile_main_profile') ;
  variable_del('account_profile_redirect') ;
  variable_del('account_profile_edit_tab') ; 
}